-- weaponskill unlock + job usability.
-- kind: quest (lv71+ WS quest) | relic | empyrean | aeonic | mythic | prime | ambuscade | su2 | nil
-- ms: jobs that can use it as main OR sub.  mo: jobs that can use it as MAIN only.
return {
  ["Aeolian Edge"] = { ms="BRD DNC NIN RDM RNG THF" },
  ["Apex Arrow"] = { kind="aeonic", ms="RNG SAM" },
  ["Arching Arrow"] = { ms="BST DRK NIN PLD RDM SAM THF WAR", mo="RNG" },
  ["Armor Break"] = { ms="DRK RUN WAR" },
  ["Ascetic's Fury"] = { kind="mythic", ms="MNK" },
  ["Asuran Fists"] = { kind="quest", ms="BST DNC DRK MNK NIN PUP RDM THF WAR" },
  ["Atonement"] = { kind="mythic", ms="PLD" },
  ["Avalanche Axe"] = { ms="BST DRK RNG RUN WAR" },
  ["Backhand Blow"] = { ms="DNC MNK NIN PUP THF WAR" },
  ["Black Halo"] = { kind="quest", ms="BLM BLU GEO MNK PLD RDM SCH SMN WAR WHM" },
  ["Blast Arrow"] = { mo="RNG" },
  ["Blast Shot"] = { mo="RNG" },
  ["Blitz"] = { kind="prime", ms="BST" },
  ["Bora Axe"] = { ms="BST DRK RNG RUN WAR" },
  ["Brainshaker"] = { ms="BLM BLU BRD BST DRG DRK GEO MNK NIN PLD PUP RDM RNG SAM SCH SMN THF WAR WHM" },
  ["Burning Blade"] = { ms="BLU BRD BST COR DNC DRG DRK NIN PLD RDM RNG RUN SAM THF WAR" },
  ["Calamity"] = { mo="BST WAR" },
  ["Camlann's Torment"] = { kind="empyrean", ms="DRG" },
  ["Cataclysm"] = { ms="MNK PLD WAR WHM" },
  ["Catastrophe"] = { kind="relic", ms="DRK" },
  ["Chant du Cygne"] = { kind="empyrean", ms="BLU PLD RDM" },
  ["Circle Blade"] = { ms="BLU BRD BST COR DNC DRG DRK NIN PLD RDM RNG RUN SAM THF WAR" },
  ["Cloudsplitter"] = { kind="empyrean", ms="BST WAR" },
  ["Combo"] = { ms="DNC MNK NIN PUP THF WAR" },
  ["Coronach"] = { kind="relic", ms="RNG" },
  ["Crescent Moon"] = { ms="DRK PLD RUN WAR" },
  ["Cross Reaper"] = { ms="BLM BST WAR", mo="DRK" },
  ["Cyclone"] = { ms="BRD DNC NIN RDM RNG THF" },
  ["Dagan"] = { kind="empyrean", ms="WHM" },
  ["Dagda"] = { kind="prime", ms="GEO WHM" },
  ["Dancing Edge"] = { mo="DNC THF" },
  ["Dark Harvest"] = { ms="BLM BST DRK WAR" },
  ["Death Blossom"] = { kind="mythic", ms="RDM" },
  ["Decimation"] = { kind="quest", ms="BST DRK RNG RUN WAR" },
  ["Detonator"] = { kind="quest", ms="COR RNG" },
  ["Diarmuid"] = { kind="prime", ms="DRG" },
  ["Dimidiation"] = { kind="mythic", ms="RUN" },
  ["Disaster"] = { kind="prime", ms="WAR" },
  ["Double Thrust"] = { ms="DRG PLD SAM WAR" },
  ["Dragon Kick"] = { ms="BST DNC DRK NIN RDM THF WAR", mo="MNK PUP" },
  ["Drakesbane"] = { kind="mythic", ms="DRG" },
  ["Dulling Arrow"] = { ms="RNG" },
  ["Earth Crusher"] = { ms="GEO MNK PLD WAR WHM" },
  ["Empyreal Arrow"] = { kind="quest", ms="BST DRK NIN PLD RDM RNG SAM THF WAR" },
  ["Energy Drain"] = { ms="BRD DNC NIN RDM RNG THF" },
  ["Energy Steal"] = { ms="BLM BRD BST COR DNC DRG DRK GEO NIN PLD PUP RDM RNG SAM SCH SMN THF WAR" },
  ["Entropy"] = { kind="aeonic", ms="BST DRK WAR" },
  ["Evisceration"] = { kind="quest", ms="BRD BST COR DNC NIN PUP RDM RNG THF WAR" },
  ["Exenterator"] = { kind="aeonic", ms="BRD BST COR DNC NIN RDM RNG THF WAR" },
  ["Expiacion"] = { kind="mythic", ms="BLU" },
  ["Exudation"] = { kind="mythic", ms="GEO" },
  ["Fast Blade"] = { ms="BLU BRD BST COR DNC DRG DRK NIN PLD RDM RNG RUN SAM THF WAR" },
  ["Fell Cleave"] = { ms="DRK RUN WAR" },
  ["Fimbulvetr"] = { kind="prime", ms="DRK PLD RUN WAR" },
  ["Final Heaven"] = { kind="relic", ms="MNK" },
  ["Flaming Arrow"] = { ms="RNG" },
  ["Flash Nova"] = { ms="BLU DRK GEO PLD SAM WAR WHM" },
  ["Flat Blade"] = { ms="BLU BRD BST COR DNC DRG DRK NIN PLD RDM RNG RUN SAM THF WAR" },
  ["Freezebite"] = { ms="DRK PLD RUN WAR" },
  ["Frostbite"] = { ms="DRK PLD RUN WAR" },
  ["Full Break"] = { ms="DRK RUN", mo="WAR" },
  ["Full Swing"] = { ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Gale Axe"] = { ms="BST DRK RNG RUN WAR" },
  ["Garland of Bliss"] = { kind="mythic", ms="SMN" },
  ["Gate of Tartarus"] = { kind="relic", ms="BLM SMN" },
  ["Geirskogul"] = { kind="relic", ms="DRG" },
  ["Ground Strike"] = { kind="quest", ms="DRK PLD RUN WAR" },
  ["Guillotine"] = { mo="DRK" },
  ["Gust Slash"] = { ms="BLM BRD BST COR DNC DRG DRK GEO NIN PLD PUP RDM RNG SAM SCH SMN THF WAR" },
  ["Hard Slash"] = { ms="DRK PLD RUN WAR" },
  ["Heavy Shot"] = { ms="DRK THF WAR", mo="RNG" },
  ["Heavy Swing"] = { ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Herculean Slash"] = { ms="DRK PLD RUN WAR" },
  ["Hexa Strike"] = { ms="PLD WAR", mo="GEO WHM" },
  ["Hot Shot"] = { ms="COR RNG" },
  ["Howling Fist"] = { mo="MNK PUP" },
  ["Imperator"] = { kind="prime", ms="BLU PLD RDM" },
  ["Impulse Drive"] = { kind="quest", ms="DRG PLD SAM WAR" },
  ["Infernal Scythe"] = { ms="BLM BST DRK WAR" },
  ["Insurgency"] = { kind="mythic", ms="DRK" },
  ["Iron Tempest"] = { ms="DRK RUN WAR" },
  ["Jishnu's Radiance"] = { kind="empyrean", ms="RNG" },
  ["Judgment"] = { ms="BLU DRK GEO PLD SAM WAR WHM" },
  ["Keen Edge"] = { ms="DRK RUN WAR" },
  ["King's Justice"] = { kind="mythic", ms="WAR" },
  ["Knights of Round"] = { kind="relic", ms="PLD RDM" },
  ["Last Stand"] = { kind="aeonic", ms="COR RNG THF" },
  ["Leaden Salute"] = { kind="mythic", ms="COR" },
  ["Leg Sweep"] = { ms="DRG PLD SAM WAR" },
  ["Mandalic Stab"] = { kind="mythic", ms="THF" },
  ["Maru Kala"] = { kind="prime", ms="MNK PUP" },
  ["Mercy Stroke"] = { kind="relic", ms="BRD RDM THF" },
  ["Metatron Torment"] = { kind="relic", ms="WAR" },
  ["Mistral Axe"] = { ms="DRK RUN", mo="BST WAR" },
  ["Moonlight"] = { ms="BLU DRK GEO PLD SAM WAR WHM" },
  ["Mordant Rime"] = { kind="mythic", ms="BRD" },
  ["Myrkr"] = { kind="empyrean", ms="BLM SCH SMN" },
  ["Mystic Boon"] = { kind="mythic", ms="WHM" },
  ["Namas Arrow"] = { kind="relic", ms="RNG SAM" },
  ["Nightmare Scythe"] = { ms="BLM BST DRK WAR" },
  ["Numbing Shot"] = { ms="COR RNG" },
  ["Omniscience"] = { kind="mythic", ms="SCH" },
  ["One Inch Punch"] = { mo="MNK PUP" },
  ["Onslaught"] = { kind="relic", ms="BST" },
  ["Origin"] = { kind="prime", ms="DRK" },
  ["Oshala"] = { kind="prime", ms="BLM SCH SMN" },
  ["Penta Thrust"] = { ms="DRG PLD SAM WAR" },
  ["Piercing Arrow"] = { ms="RNG" },
  ["Power Slash"] = { ms="DRK PLD RUN WAR" },
  ["Primal Rend"] = { kind="mythic", ms="BST" },
  ["Pyrrhic Kleos"] = { kind="mythic", ms="DNC" },
  ["Quietus"] = { kind="empyrean", ms="DRK" },
  ["Raging Axe"] = { ms="BST DRK RNG RUN WAR" },
  ["Raging Fists"] = { mo="MNK PUP" },
  ["Raging Rush"] = { mo="WAR" },
  ["Raiden Thrust"] = { ms="DRG PLD WAR" },
  ["Rampage"] = { ms="BST DRK RNG RUN WAR" },
  ["Randgrith"] = { kind="relic", ms="WHM" },
  ["Realmrazer"] = { kind="aeonic", ms="BLM BLU GEO MNK PLD SCH SMN WAR WHM" },
  ["Red Lotus Blade"] = { ms="BLU DRK PLD RDM RUN WAR" },
  ["Refulgent Arrow"] = { ms="RNG" },
  ["Requiescat"] = { kind="aeonic", ms="BLU COR DRK PLD RDM RUN SAM WAR" },
  ["Resolution"] = { kind="aeonic", ms="DRK PLD RUN WAR" },
  ["Retribution"] = { kind="quest", ms="BLM BRD BST DRG GEO MNK PLD RDM SCH SMN WAR WHM" },
  ["Rock Crusher"] = { ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Rudra's Storm"] = { kind="empyrean", ms="BRD DNC THF" },
  ["Ruinator"] = { kind="aeonic", ms="BST DRK RNG RUN WAR" },
  ["Ruthless Stroke"] = { kind="prime", ms="BRD DNC RDM THF" },
  ["Sanguine Blade"] = { ms="BLU DRK PLD RDM RUN WAR" },
  ["Sarv"] = { kind="prime", ms="RNG" },
  ["Savage Blade"] = { kind="quest", ms="BLU BRD BST COR DRG DRK NIN PLD RDM RNG RUN THF WAR" },
  ["Scourge"] = { kind="relic", ms="DRK PLD WAR" },
  ["Seraph Blade"] = { ms="BLU DRK PLD RDM RUN WAR" },
  ["Seraph Strike"] = { ms="BLU DRK GEO PLD SAM WAR WHM" },
  ["Shadow of Death"] = { ms="DRK WAR" },
  ["Shadowstitch"] = { ms="BLM BRD BST COR DNC DRG DRK GEO NIN PLD PUP RDM RNG SAM SCH SMN THF WAR" },
  ["Shark Bite"] = { ms="BLM GEO SCH SMN", mo="DNC THF" },
  ["Shattersoul"] = { kind="aeonic", ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Shell Crusher"] = { ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Shield Break"] = { ms="DRK RUN WAR" },
  ["Shijin Spiral"] = { kind="aeonic", ms="MNK PUP" },
  ["Shining Blade"] = { ms="BLU BRD BST COR DNC DRG DRK NIN PLD RDM RNG RUN SAM THF WAR" },
  ["Shining Strike"] = { ms="BLM BLU BRD BST DRG DRK GEO MNK NIN PLD PUP RDM RNG SAM SCH SMN THF WAR WHM" },
  ["Shockwave"] = { ms="DRK PLD RUN WAR" },
  ["Shoulder Tackle"] = { ms="DNC MNK NIN PUP THF WAR" },
  ["Sickle Moon"] = { mo="DRK PLD RUN" },
  ["Sidewinder"] = { ms="RNG" },
  ["Skewer"] = { mo="DRG" },
  ["Skullbreaker"] = { ms="BLM BLU BRD BST DRG DRK GEO MNK NIN PLD PUP RDM RNG SAM SCH SMN THF WAR WHM" },
  ["Slice"] = { ms="BLM BST DRK WAR" },
  ["Slug Shot"] = { ms="COR RNG" },
  ["Smash Axe"] = { ms="BST DRK RNG RUN WAR" },
  ["Sniper Shot"] = { ms="COR RNG" },
  ["Sonic Thrust"] = { ms="DRG PLD WAR" },
  ["Spinning Attack"] = { ms="DNC MNK NIN PUP THF WAR" },
  ["Spinning Axe"] = { ms="BST DRK WAR" },
  ["Spinning Scythe"] = { ms="BLM BST DRK WAR" },
  ["Spinning Slash"] = { ms="WAR", mo="DRK PLD RUN" },
  ["Spiral Hell"] = { kind="quest", ms="BLM BST DRK WAR" },
  ["Spirit Taker"] = { ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Spirits Within"] = { ms="BLU BRD BST COR DNC DRG DRK NIN PLD RDM RNG RUN SAM THF WAR" },
  ["Split Shot"] = { ms="COR RNG" },
  ["Starburst"] = { ms="BLM BRD DRG GEO MNK PLD SCH SMN WAR WHM" },
  ["Stardiver"] = { kind="aeonic", ms="DRG SAM WAR" },
  ["Starlight"] = { ms="BLM BLU BRD BST DRG DRK GEO MNK NIN PLD PUP RDM RNG SAM SCH SMN THF WAR WHM" },
  ["Steel Cyclone"] = { kind="quest", ms="DRK RUN WAR" },
  ["Stringing Pummel"] = { kind="mythic", ms="PUP" },
  ["Sturmwind"] = { ms="DRK RUN WAR" },
  ["Sunburst"] = { ms="GEO MNK PLD WAR WHM" },
  ["Swift Blade"] = { ms="BLU BRD COR DNC DRG DRK RDM SAM THF WAR", mo="PLD RUN" },
  ["Tachi: Ageha"] = { ms="NIN SAM" },
  ["Tachi: Enpi"] = { ms="NIN SAM" },
  ["Tachi: Fudo"] = { kind="empyrean", ms="SAM" },
  ["Tachi: Gekko"] = { ms="NIN", mo="SAM" },
  ["Tachi: Goten"] = { ms="NIN SAM" },
  ["Tachi: Hobaku"] = { ms="NIN SAM" },
  ["Tachi: Jinpu"] = { ms="NIN SAM" },
  ["Tachi: Kagero"] = { ms="NIN SAM" },
  ["Tachi: Kaiten"] = { kind="relic", ms="SAM" },
  ["Tachi: Kasha"] = { kind="quest", ms="NIN SAM" },
  ["Tachi: Koki"] = { ms="NIN SAM" },
  ["Tachi: Mumei"] = { kind="prime", ms="SAM" },
  ["Tachi: Rana"] = { kind="mythic", ms="SAM" },
  ["Tachi: Shoha"] = { kind="aeonic", ms="SAM" },
  ["Tachi: Yukikaze"] = { mo="SAM" },
  ["Terminus"] = { kind="prime", ms="COR RNG" },
  ["Thunder Thrust"] = { ms="DRG PLD SAM WAR" },
  ["Torcleaver"] = { kind="empyrean", ms="DRK PLD" },
  ["Tornado Kick"] = { ms="MNK PUP" },
  ["True Strike"] = { ms="BLM BLU BRD BST DRG DRK GEO MNK NIN PLD PUP RDM RNG SAM SCH SMN THF WAR WHM" },
  ["Trueflight"] = { kind="mythic", ms="RNG" },
  ["Ukko's Fury"] = { kind="empyrean", ms="WAR" },
  ["Upheaval"] = { kind="aeonic", ms="DRK RUN WAR" },
  ["Victory Smite"] = { kind="empyrean", ms="MNK PUP" },
  ["Vidohunir"] = { kind="mythic", ms="BLM" },
  ["Viper Bite"] = { ms="BRD DNC NIN RDM RNG THF" },
  ["Vorpal Blade"] = { ms="BLU DRK PLD RDM RUN WAR" },
  ["Vorpal Scythe"] = { ms="BLM BST DRK WAR" },
  ["Vorpal Thrust"] = { ms="DRG PLD SAM WAR" },
  ["Wasp Sting"] = { ms="BLM BRD BST COR DNC DRG DRK GEO NIN PLD PUP RDM RNG SAM SCH SMN THF WAR" },
  ["Weapon Break"] = { ms="DRK RUN WAR" },
  ["Wheeling Thrust"] = { ms="PLD SAM WAR", mo="DRG" },
  ["Wildfire"] = { kind="empyrean", ms="COR RNG" },
}
